### ISSUE TITLE
Make sure the blob clears for subsequent requests. 

### ISSUE THREAD

**Issue by geohacker** [mapbox/osm-query#2]
https://github.com/mapbox/osm-query/blob/master/js/app.js#L77

**Comment by ramyaragupathy** [comment]
@geohacker blob is cleared up each time submit button is hit.

**Comment by geohacker** [comment]
Can you try this? It didn't seem to work for me.

**Comment by geohacker** [comment]
Steps to reproduce:
1. Run a query
2. Click on the download link
3. Run another query in the same instance (don't refresh osm-query)
4. Click on the download link
5. Notice that the geojson is same as the previous request.

**Comment by ramyaragupathy** [comment]
Hey, just integrated an option to download file. Did a quick diff check with the files and data seems fine.
