### ISSUE TITLE
Overpass request fails

### ISSUE THREAD

**Issue by ramyaragupathy** [mapbox/osm-query#23]
Queries through `http://overpass.osm.rambler.ru/` returns `404` error. Attaching a screenshot here.
![screenshot 2015-10-30 15 39 07](https://cloud.githubusercontent.com/assets/12103383/10843065/605a4b04-7f1c-11e5-942e-0f654b75c349.png)

However queries through `https://www.overpass-api.de` works fine.

cc @geohacker @batpad

**Comment by maning** [comment]
Is it possible for the app to switch automatically to [another overpass endpoint](http://wiki.openstreetmap.org/wiki/Overpass_API#Introduction) when one fails?

**Comment by geohacker** [comment]
@maning nice idea. it should be able to.
