### ISSUE TITLE
Results doesn't match with real editions

### ISSUE THREAD

**Issue by samely** [mapbox/osm-query#29]
I got the numbers of buildings traced on Monday January 4th. 

This is what I got:
![image](https://cloud.githubusercontent.com/assets/10425629/12130060/c223ec94-b3d5-11e5-86ca-3100848fe0ae.png)

But I have some non concordance with Ruben and Luis editions
- [Ruben's editions](https://www.dropbox.com/s/b1cpe9tkb99s862/210-Rub21.osm?dl=0)
  He didn't trace any building, but osm-query shows **887** traced buildings.
- Luis has traced **1009** buildings but osm-query shows **1678**.
  ![image](https://cloud.githubusercontent.com/assets/10425629/12148801/734ac7fc-b46e-11e5-8738-4e240834e0bc.png)

@ramyaragupathy @Rub21

**Comment by ramyaragupathy** [comment]
I ran [a query](http://overpass-turbo.eu/s/dCO) for this directly in overpass and this seems to return the same numbers @samely. But the edits highlighted for @Rub21 is dated one year ago! not sure what is causing this error. I will further investigate on this.
