### ISSUE TITLE
Fetch `ways` and `relations` in different requests

### ISSUE THREAD

**Issue by geohacker** [mapbox/osm-query#3]
Fetch ways and relations in different requests (to avoid Overpass memory leaks) and concat the geojson.

**Comment by ramyaragupathy** [comment]
Begun working on this. Should be in place before EoD today.

**Comment by planemad** [comment]
Punt on relations for now. We don't usually edit relations and it increases the query response time significantly

**Comment by ramyaragupathy** [comment]
Part of sprint 1 #15
